### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by ss18** [oleksiyp/mockk#14]
dsl/common/src/main/kotlin/io/mockk/Matchers.kt comparision -> comparison
agent/src/main/java/io/mockk/proxy/MockKInstrumentation.java tranform -> transform

**Comment by oleksiyp** [comment]
Thanks, will fix it

3 янв. 2018 г. 12:10 PM пользователь "Semen Zhydenko" <
notifications@github.com> написал:
