### ISSUE TITLE
how to match varags?

### ISSUE THREAD

**Issue by dtanner** [oleksiyp/mockk#16]
I don't see how to create a mock match for a function accepting varargs.  Is that supported?  Thanks.

**Comment by oleksiyp** [comment]
Vararg support was implemented as far as I remember. All you need is just use matchers instead of values in `every` block. It allows to have only the same number of arguments, so a little bit not so flexible. I'll try it in a moment

**Comment by oleksiyp** [comment]
Like that:
```kotlin
class Vararg {
    fun fn(a: Int, vararg b: Int, c: Int) = a + b.sum() + c
}

fun main(args: Array<String>) {
    val m = mockk<Vararg>()

    every { m.fn(1, more(3), c=4) } returns 1
    every { m.fn(1, more(3), more(4), c=4) } returns 2
    every { m.fn(1, more(3), more(4), more(5), c=4) } returns 3

    println(m.fn(1, 4, c=4)) //1
    println(m.fn(1, 4, 5, c=4)) //2
    println(m.fn(1, 4, 5, 6, c=4)) //3
}
```

**Comment by dtanner** [comment]
ahhh - thanks!
