### ISSUE TITLE
Is there a way to mock a property value?

### ISSUE THREAD

**Issue by s1vert** [oleksiyp/mockk#17]
When I use the following code to mock a property value, I get nulls.
```
    private val view = mockk<LoginView>(relaxed = true)
    private val auth = mockk<AuthenticationManager>(relaxed = true)
    private val presenter = LoginPresenter(auth)

    @Test
    fun onSignInClicked_loginInvalid_showError(){
        every { view.login } returns "dd"
        every { view.password } returns "password"

        presenter.onSignInClicked()
...
```
Is there a workaround for this problem or am I missing something?

**Comment by oleksiyp** [comment]
Can you paste stack trace? And point what line is throwing exception?

**Comment by s1vert** [comment]
Actually I found a silly mistake in my code and now everything is working fine. Sorry for bothering you.

**Comment by oleksiyp** [comment]
No problems. Ask more if have any issues/questions (in GH issue or gitter)

2018-01-25 15:02 GMT+01:00 Tomasz Stankowski <notifications@github.com>:
