### ISSUE TITLE
Add optional argument to function mockk to configure created mock

### ISSUE THREAD

**Issue by gildor** [oleksiyp/mockk#20]
Now we have a lot of cases when we create mock and want to configure it on the place (usually set `every` for methods).
To do that now we use `apply`:
```kotlin
val someMock: SomeClass = mockk().apply {
    every { someMethod() } returns "Foo"
}
```

Would be helpful to have mock configuration lambda with receiver as the latest argument in mockk:
Now
```kotlin
inline fun <reified T : Any> mockk(
    name: String? = null,
    relaxed: Boolean = false,
    vararg moreInterfaces: KClass<*>
): T
```

After:
```kotlin
inline fun <reified T : Any> mockk(
        name: String? = null,
        relaxed: Boolean = false,
        vararg moreInterfaces: KClass<*>,
        block: T.() -> Unit = {} // Cannot be null, but we can reuse cached instance to avoid calling empty block
): T
```

so now you can use `mockk` this way:
```kotlin
val someMock: SomeClass = mockk {
    every { someMethod() } returns "Foo"
}
```

Also works with all other optional arguments

**Comment by oleksiyp** [comment]
@gildor please check version 1.7.2 with applied changes and close ticket if everything is OK

**Comment by jewer** [comment]
Just started using this syntax this morning.  Very nice! 👍

**Comment by gildor** [comment]
@oleksiyp  Hi! Thats' great! Just checked with our project. Really appreciate so fast reaction.
Great library, hope to contribute in the future

**Comment by gildor** [comment]
Fixed
