### ISSUE TITLE
Not able to mock for return type as Arrow#Either

### ISSUE THREAD

**Issue by anirbansingharoy** [oleksiyp/mockk#21]
I am trying mock a method call which returns of Either type of  Arrow Library. But i am getting below exception when writing the Mock behaviour 
code : `every { /*somemethod call*/ }.returns(Either.left(/*Some object*/)`

Exception 
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Incorrect resolution sequence for Java field public final val isLeft: kotlin.Boolean defined in arrow.core.`Either$ByteBuddy$0FhSn1dn`[JavaPropertyDescriptor@3c49fab6] (source = null)
Is this something to be fixed in the library or its not at all support shield classes ?

**Comment by oleksiyp** [comment]
Let me check that

**Comment by oleksiyp** [comment]
Code:
```
    class Cls {
        fun fn(): Either<String, String> = Either.right("def")
    }

    val mock: Cls = mockk {
        every { fn() }.returns(Either.left("abc"))
    }

    println(mock.fn())
```
outputs:
```
Left(a=abc)
```

**Comment by oleksiyp** [comment]
Can you double check again the issue? If it still valid, then just send a gist with all required code + version of Arrow. Thank you!

**Comment by anirbansingharoy** [comment]
I am able to resolve the by upgrading io.mockk to 1.7.2 . Earlier we were running on 1.6.3
