### ISSUE TITLE
Verify inline functions with reified and crossinline params

### ISSUE THREAD

**Issue by kristiyanP** [oleksiyp/mockk#27]
Is it possible to verify a function like this?
```kotlin 
inline fun <reified T> Socket.emitTyped(event: String,
                                        objectToEmit: Any?,
                                        crossinline success: (response: T) -> Unit,
                                        crossinline error: (reason: String) -> Unit) 
```

**Comment by oleksiyp** [comment]
@kristiyanP, unfortunately, it is not possible as no method with bytecode is produced. I heard this question already few times. It would require a totally different approach to solve. For example writing an annotation processor. I am thinking about it, as this can probably make it possible to run on Android devices.

**Comment by sriharshachilakapati** [comment]
Why not wrap it in a regular function and test that instead? Wouldn't that work?

```kotlin
inline fun <reified T> Socket.emitTyped(event: String,
                                        objectToEmit: Any?,
                                        crossinline success: (response: T) -> Unit,
                                        crossinline error: (reason: String) -> Unit) {
    // Some code which gets inlined
}

fun <T> emitTypedWrapper(event: String,
                                        objectToEmit: Any?,
                                        success: (response: T) -> Unit,
                                        error: (reason: String) -> Unit) {
    // This will be replaced with code inside the inline function by compiler
    Socket.emitTyped(event, objectToEmit, success, error)
}
```
Now write your tests with the wrapper function.

**Comment by paypulse** [comment]
Hi , this is my first comment 
But, kotlin has a reified restrict . so, you can't use function 

Why don't you use like this.
inline fun <reified T> testEmitTyped(...) {
    socket.emitTyped<T>(...)
}
