### ISSUE TITLE
NoClassDefFoundError: KClasses

### ISSUE THREAD

**Issue by yannickvg** [oleksiyp/mockk#3]
When running my tests with version 1.4, I get the following error on all my tests: 

```
java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at io.mockk.impl.MockFactoryImpl.mockk(Factory.kt:27)
```
Exactly the same tests with version 1.3 works fine.

**Comment by oleksiyp** [comment]
Oh, that is due dependeny issue. Not good. Try linking kotlin reflaction

**Comment by oleksiyp** [comment]
compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

Will fix it today via new release

**Comment by yannickvg** [comment]
That dependency was indeed missing, thanks

**Comment by oleksiyp** [comment]
@yannickvg please check 1.4.1 version without specifying kotlin-reflection dependency in your project. Many thanks for figuring this out

**Comment by yannickvg** [comment]
No problem, version 1.4.1 without dependency works fine!
