### ISSUE TITLE
Missing Feature?  Mocking dynamic type

### ISSUE THREAD

**Issue by a1flecke** [oleksiyp/mockk#31]
Use Case:  In mockito I was doing this:
```java
private void assertRequestClassWasUsed(final Class<? extends AbstractRequest> requestKlass, Runnable doIt, Consumer<QueueWriter> verification) {
        final QueueWriter queueWriter = expectedQueueWriter.get(requestKlass);
        assertThat(queueWriter).as("Could not find queuewriter for payload %s", requestKlass.getCanonicalName()).isNotNull();
        final AbstractRequest request = (AbstractRequest)mock(requestKlass);  //<-- This
        when(queueWriter.getName()).thenReturn(QUEUE_NAME);
        when(message.getPayload()).thenReturn(request);
        when(receivedMessage.getPayload()).thenReturn(request);
        doIt.run();
        verification.accept(queueWriter);
        Mockito.reset(primaryQueueWriter, refreshQueueWriter, harvestQueueWriter, createQueueWriter);
```

I cannot figure out a way in mockk to do the equivalent of `mock(requestClass)` where the class is not known at compile time.  I fully admit that I am missing something here.

**Comment by oleksiyp** [comment]
This is to be added. I was thinking about use cases before and it seems for me pretty weird. For plugins/extensions and less "user-facing" things there is direct Gateway API that can be used.

**Comment by a1flecke** [comment]
@oleksiyp Thanks.

**Comment by oleksiyp** [comment]
Gateway API should be okay if you do it once. Check #23

**Comment by oleksiyp** [comment]
I think I can easily add something alike `classMockk`, as your case is not extension or plugin. #23 was exactly about JUnit extension

**Comment by oleksiyp** [comment]
Check http://mockk.io/#class-mock and close ticket if it fulfills your request

**Comment by a1flecke** [comment]
Sounds good. The other piece that I ended up needing was resetting the
mocks call count.  I ended up grabbing a reference to the callrecorder and
calling reset. I suspect this “resets the world “ and not just the
individual mocks. A little heavy handed, but it works for now.

I can file a separate issue about that if you prefer.

Aaron

**Comment by oleksiyp** [comment]
Hm, looks something is going wrong, but I don't understand why you require calling "reset". 

It is not "reset the world" actually. 

This reset is rather local for "every" and "verify" constructs. It is resetting state machine that controls recording state(i.e. one when calls are recorded for verification/stubbing) vs normal state(when it is just called). It is in public API because useful to be called for example before tests via some testing framework extensions to isolate tests.

Have you checked `clearMocks` function? Why is it not fitting your needs?

**Comment by a1flecke** [comment]
@oleksiyp 

>Have you checked clearMocks function? Why is it not fitting your needs?
I must have missed this.  Switched to using this.  Thanks.
