### ISSUE TITLE
Verify failing with arguments not matching

### ISSUE THREAD

**Issue by Kerooker** [oleksiyp/mockk#32]
Relevant [StackOverflow](https://stackoverflow.com/questions/48909220/mockk-verify-failing-with-arguments-not-matching)

I've noticed that sometimes verify fails with "... call to ... happened, but arguments are not matching"

Here is a sample test that shows verify failing:

```
class TestStuff {

    val stuff = "1"

    @RelaxedMockK
    lateinit var testService: TestService

    @RelaxedMockK
    lateinit var testInterface: TestInterface

    @Before
    fun setup() {
        MockKAnnotations.init(this)

        every { testInterface.testStuff } returns stuff
    }

    @Test
    fun testStuffCalled() {
        testService.testStuff(testInterface.testStuff)

        verify { testService.testStuff(testInterface.testStuff) }
    }
}

interface TestInterface {
    val testStuff: String
}

class TestService {

    fun testStuff(stuff: String) {
    }
}
```

**Comment by oleksiyp** [comment]
It is impossible to mock strings, objects are probably not working as well for this compound verify. I need to check.

Anyway it should work if you check it separately.
