### ISSUE TITLE
StackOverflowException with HashMap

### ISSUE THREAD

**Issue by novaterata** [oleksiyp/mockk#35]
I think this might be related to https://github.com/mockito/mockito/issues/818 as maybe it was ported from the culprit over there. 
I'm using 1.7.8 and actually in my case I'm not mocking a HashMap, but returning one from an every block
    
     val blob : CloudBlockBlob = mockk() // from azure-storage-java  
     val metadata : HashMap<String?,String?> = hashMapOf()
     every { blob.metadata } returns metadata

The StackOverflowException occurs when blob calls metadata. I don't know why HashMap is getting mocked though.
Honestly I don't know what is happening but that mockito bug looked too similar to ignore

    Exception in thread "main" java.lang.StackOverflowError
	at java.lang.Class.getDeclaredMethod(Class.java:2127)
	at java.util.HashMap.get(HashMap.java:556)
	at sun.reflect.Reflection.filterMethods(Reflection.java:291)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

**Comment by oleksiyp** [comment]
Thanks for reporting it. Indeed class transformation is very similar to Mockito.

**Comment by oleksiyp** [comment]
The fix is here, it is a little bit ugly, but should be OK. To make it really nice, a ByteBuddy should be changed.

**Comment by novaterata** [comment]
Thanks, I'm using a workaround now, I'll test after the next release when I have some down time

**Comment by oleksiyp** [comment]
Version 1.7.10 released, please check if it fixes your case and close the ticket.

**Comment by novaterata** [comment]
That fixed it thanks!
