### ISSUE TITLE
Windows-Defender-unfriendly temp file created every time run tests

### ISSUE THREAD

**Issue by phuctm97** [oleksiyp/mockk#40]
Mockk when boostrapping create a temp file that makes Windows Defender confused and then asks me to check if the file is safe all the time

![image](https://user-images.githubusercontent.com/25026967/37209440-e8521dae-23d7-11e8-8d26-4adcc066e416.png)

**Comment by oleksiyp** [comment]
@raphw can you suggest on this as well?

**Comment by raphw** [comment]
Byte Buddy needs to create a jar file for the auto attachment. Its a temporary Java agent which must be stored on disk.

**Comment by oleksiyp** [comment]
Is mockito facing same issue? Or defender knows it? (Sorry has no windows
setup)

9 марта 2018 г. 4:29 PM пользователь "Rafael Winterhalter" <
notifications@github.com> написал:

**Comment by phuctm97** [comment]
@oleksiyp no, mockito just works fine!

**Comment by oleksiyp** [comment]
I'm trying to submit it here: https://www.microsoft.com/en-us/wdsi/filesubmission 

@phuctm97 can you follow the manual [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#detection-history) to get "Detection name *" which is required to submit form OR try submitting it yourself.

**Comment by raphw** [comment]
That is very strange but I assume it is the naming change that causes the detection. I assume the Byte Buddy prefixed version is whitelisted.

**Comment by oleksiyp** [comment]
This file doesn't contain any ByteBuddy files. It contains Dispatcher + Weak Map and this is similar to Mockito classes, but not totally identical.

**Comment by phuctm97** [comment]
After several days, Windows Depender could have recognized those files are safe and no more warning!

**Comment by oleksiyp** [comment]
Anyway thanks!

**Comment by anderius** [comment]
So Defender should ignore the files now? It still warns on my computer, threat definition is 1.263.509.0.

**Comment by phuctm97** [comment]
Yub, exactly, Depender gradually ignores those files, at the very first, it cried all the time I run tests, then usually, then sometimes and now it's off.
