### ISSUE TITLE
Broken JDK7 compatibility

### ISSUE THREAD

**Issue by monosoul** [oleksiyp/mockk#43]
Mockk 1.7.9 (and all other versions I guess) is currently unable to run under JDK7 due to forEach lambda in `JvmAutoHinter` for example.

**Comment by monosoul** [comment]
@oleksiyp if you don't mind I'd be glad to dig deeper into that problem.

**Comment by oleksiyp** [comment]
Very welcome

**Comment by monosoul** [comment]
@oleksiyp Hey, thanks for merging! :smile: Is there any chance of releasing new version anytime soon?

**Comment by oleksiyp** [comment]
Most probable it will happen today in the evening

**Comment by monosoul** [comment]
Nice, thank you!

**Comment by monosoul** [comment]
Everything is working as expected now. Thanks!
