### ISSUE TITLE
How to run it with Android Instrumentation Tests

### ISSUE THREAD

**Issue by shidobecker** [oleksiyp/mockk#45]
I've been trying to run mockk with androi instrumentation test but no success.
I've added     **testCompile "io.mockk:mockk:1.7.10"**
To my build.gradle
And I was able to run it perfectly as a unit test.
But if I try to run as an Instrumentation Test, I get a unresolved reference in _io.mockk.*_

If I add : 
**androidTestCompile "io.mockk:mockk:1.7.10"**

I was able to build it, doesnt get the unresolved reference anymore, but when I run the test I got:
**java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/instrument/ClassFileTransformer;**

Is there something I'm doing wrong, I really wish to use mockk it with android instrumentation tests.

Here is my Test section in my build.gradle

`  
     

    testCompile 'org.mockito:mockito-core:2.7.22'

    androidTestCompile 'org.mockito:mockito-android:2.7.22'

    androidTestCompile 'io.mockk:mockk:1.7.10'

    testCompile 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0'

    testImplementation 'org.hamcrest:hamcrest-library:1.3'

    testImplementation "com.squareup.retrofit2:retrofit-mock:${retrofitLibVersion}"

    testImplementation 'org.mockito:mockito-inline:2.13.0'

    testCompile ('org.threeten:threetenbp:1.3.2'){
        exclude group:'com.jakewharton.threetenabp', module:'threetenabp'
    }
    testCompile 'junit:junit:4.12'
    testCompile "io.mockk:mockk:1.7.10"
`

**Comment by oleksiyp** [comment]
Same thing as here: https://github.com/oleksiyp/mockk/issues/39

**Comment by oleksiyp** [comment]
Closing as duplicate #39. Soon to be resolved
