### ISSUE TITLE
Properties are not supported as DynamicCalls

### ISSUE THREAD

**Issue by Albert-Gao** [oleksiyp/mockk#51]
From Gitter.

I want to test some actions against a protected property. Don't know how. I create a gist with simple example: https://gist.github.com/Albert-Gao/e546a8f2ea6d6be0b766c30dab476dbe Any help here?

**Comment by oleksiyp** [comment]
Version 1.7.15 is released(syncing to central repo during next half an hour). You can try it out and close the ticket if it fulfills it.

Syntax is following(added this to README):

```
val mock = spyk(Team(), recordPrivateCalls = true)

every { mock getProperty "speed" } returns 33
every { mock setProperty "acceleration" value less(5) } just Runs
every { mock invoke "openDoor" withArguments listOf("left", "rear") } returns "OK"

verify { mock getProperty "speed" }
verify { mock setProperty "acceleration" value less(5) }
verify { mock invoke "openDoor" withArguments listOf("left", "rear") }
```

**Comment by Albert-Gao** [comment]
very readable syntax
tried, works! thx
