### ISSUE TITLE
Cannot objectMockk inline function

### ISSUE THREAD

**Issue by rickcodetalk** [oleksiyp/mockk#55]
I tried to objectMockk an inline function of an object and it didn't seem to work. 

I did sth like 

`    
    @BeforeAll
    fun beforeTests() {

        objectMockk(MockObj).mock()

        every { MockObj.getSth<Room>(1) } returns 1
    }
`
and the getSth is simply like:

`
    inline fun <reified T> getSth(): String {
        return (T::class.annotations.find { it is MongoDBCollection } as MongoDBCollection).name
    }
`

and it throws 

`=> io.mockk.MockKException: Missing calls inside every { ... } block`

Is that mocking of inline function is not supported?

Thanks.

**Comment by oleksiyp** [comment]
The issue is not fixable, as mockk as well as other mocking libraries rely
on bytecode level instrumentation for methods. And inline just do not
generate any methods

ср, 4 апр. 2018 г., 7:35 Rick Lee <notifications@github.com>:
