### ISSUE TITLE
Class cast exception while mocking MutableList

### ISSUE THREAD

**Issue by igorvilela28** [oleksiyp/mockk#57]
Hello,

I'm having problems to mock a mutable list. 

My use case is that I simple want a mock for a mutableList and specify what list to return in the `mutableList.toList()`  call. But when I try to assert the result, I get a class cast exception:

```
java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.Integer
```

Here a simple code that shows the problem:

```
class Test () {

    val mutableList = mockk<MutableList<String>>()

    @Test
    fun test() {

        val expectedList = listOf("1")
        every { mutableList.toList() } returns expectedList

        val list = mutableList.toList()
        Assert.assertEquals(expectedList, list)

    }
}
```

**Comment by oleksiyp** [comment]
This is happening because `toList` is an extension function, which should be mocked other way than regular function.
```
public fun <T> Iterable<T>.toList(): List<T> {
    if (this is Collection) {
        return when (size) {
            0 -> emptyList()
            1 -> listOf(if (this is List) get(0) else iterator().next())
            else -> this.toMutableList()
        }
    }
    return this.toMutableList().optimizeReadOnlyList()
}
```
Although the error message is misleading. I'll keep the ticket to fix the error message.

You can workaround this test using following code:
```
    val mutableList = mockk<MutableList<String>>()

    @Test
    fun test() {
        every { mutableList.size } returns 1
        every { mutableList.get(0) } returns "1"

        val list = mutableList.toList()
        assertEquals(listOf("1"), list)
    }
```
staticMockk which is usually helps to mock extensions, didn't work for me. Probably because collections are used in mockk itself

**Comment by igorvilela28** [comment]
Thanks. I've checked the workaround and it's working.
