### ISSUE TITLE
Are there any analogues Mockito.verifyNoMoreInteractions(), Mockito.verifyZeroInteractions() ?

### ISSUE THREAD

**Issue by alexxxdev** [oleksiyp/mockk#6]

**Comment by oleksiyp** [comment]
Check PR #2. You basically can verify call happened exactly 0 times

**Comment by alexxxdev** [comment]
this works for `verify(exactly = 0) { foo.bar() }`
but it is not working for `verify(exactly = 0) { foo }` similarly `Mockito.verifyNoMoreInteractions(foo)`

**Comment by oleksiyp** [comment]
Ok, I'll consider adding it. Probably in today's night release

**Comment by oleksiyp** [comment]
And thanks for reporting. Maybe any suggestions on how to do that? Anything else to add?

**Comment by alexxxdev** [comment]
Thx.
I think it's worth to see how this is implemented in Mockito
I just started using mokk, maybe later there will be more requests

**Comment by oleksiyp** [comment]
Sorry I probabaly wasn't clear. I mean how to do it from end-user
perspective i.e. DSL syntax, e.t.c. just leave it to me if you have no
preference regarding that. but anyway c'mon :-) if I would lookup every
feature in Mockito, I would build second mockito, but worse :-)

22 нояб. 2017 г. 9:36 AM пользователь "Alexey Derendyaev" <
notifications@github.com> написал:

**Comment by alexxxdev** [comment]
Mayde, something like
`verifyNoMoreInteractions(foo, bar)`
or
```
verifyNoMoreInteractions {
   foo
   bar
}
```

**Comment by oleksiyp** [comment]
verifyNoMoreInteractions just finalizes un-ordered verification checks and verifies that nothing else was called except already verified. Basically in MockK DSL I have very similar construct `verifySequence`, but it additionally checks order.

So overall solution would introduce `verifyAll` following way: 
```kotlin
verifyAll {
  a.call1()
  b.call2()
  c.call3()
}
```
This translates to following Mockito code:
```java
verify(a).call1()
verify(b).call2()
verify(c).call3()
verifyNoMoreInteractions(a, b, c)
```
Basically this checks that there was only calls 1,2 and 3 and nothing else in arbitrary order for mocks a, b and c.

Regarding `verifyZeroIntercation`. My basic idea is following code:
```kotlin
verify {
  a wasNot Called
}
```

but than logically to add `was Called`
```kotlin
verify {
   a was Called
}
```
which means called some method at least once.

Then:
```kotlin
verify(atLeast = 5) {
   a was Called
}
```
which means called some method at least 5 times.

Or:
```kotlin
verify(atMost = 5) {
   a was Called
}
```
which means called some method at most 5 times.

And finally:
```kotlin
verifyOrder {
   a was Called
   b.def()
}
```
which means first some method of `a` was called then method of `b` called.

Similiar:
```kotlin
verifySequence {
   a was Called
   b.def()
}
```
which means first some method of a was called then method of b called and that is all interaction with mocks `a` and `b`.

Sorry for long read. I've checked the code and seems it requires few days/week effort to implement all that. I understand it's easy to just implement first two cases and other may be quite useless, but I need to think twice before starting.

**Comment by oleksiyp** [comment]
Released 1.5.4 should handle both your use-cases:
```kotlin
verifyAll { mock.call1() }
verify { mock wasNot Called }
```
Please check and close ticket if everything is OK

**Comment by alexxxdev** [comment]
Thx! I'll check it out soon

**Comment by prestuhome** [comment]
Hello. I have related problem.
I have mock with some methods. I want to be sure that method def will be called once and other methods will not be called:
`
verify(mock, only()).def()
verifyNoMoreInteractions(mockRepository)
`
So i can't use solution of the issue:
`
//java.lang.AssertionError: Verification failed: Mock(#1) should not be called
verify(exactly = 1) { mock.def() }
verify { mock wasNot Called}
`
or
`
//java.lang.AssertionError: Verification failed: Mock(#1) should not be called
verifyAll { mock.def() }
verify { mock wasNot Called}
`

**Comment by shiehnpin** [comment]
Update: In case anyone tries to use `verify { mock wasNot Called }`  to replace `verifyZeroInteractions()` but couldn't pass the test. The correct usage is `confirmVerified(mock)`.  See "Verification confirmation" section in [https://mockk.io/](https://mockk.io/)
