### ISSUE TITLE
java.lang.NoClassDefFoundError When trying to use MockK in Android Instrumentation Test

### ISSUE THREAD

**Issue by vander2675** [oleksiyp/mockk#62]
Hey,
I'm currently trying to execute a simple Android Instrumentation Unit Test, while Mocking an Dependency with MockK.

When I try to mock with:
```Kotlin
        val mockedReachability = mockk<ConnectivityManager>()
```

I get:
java.lang.NoClassDefFoundError: Failed resolution of: Lio/mockk/proxy/MockKInstrumentation;

**Comment by oleksiyp** [comment]
Basically it is not supported. https://github.com/oleksiyp/mockk/issues/39

**Comment by oleksiyp** [comment]
Sad story. 

From my side I was making first steps to reimplement Android instrumentation test support. But this is hard task. Linkedin guys wrote so much code just for that support. https://github.com/linkedin/dexmaker

**Comment by Albert-Gao** [comment]
@oleksiyp 

Haha, thanks for the tips.

Tried that before. Still has that restriction. Can't mock a 3rd party lib. Which in my case, a `.jar` file equals a 3rd party lib.

And to be honest, if the multi-platform project could support my use case. I won't need to depend on a file at all.

Anyway. Just

**Comment by oleksiyp** [comment]
Duplicate for #39. Closing. Soon to be redolved

**Comment by absentmindedguy** [comment]
So... what was the solution, then?
