### ISSUE TITLE
Changing mock properties on staticMockks

### ISSUE THREAD

**Issue by Kleinendorst** [oleksiyp/mockk#67]
Is it possible to set the type of mock/the properties of the mock when using `staticMockk`?
I'd like to set `relaxed = true` on the snippet below, but can't find documentation/any working solution of this.

```kotlin
staticMockk(KafkaSender::class.qualifiedName!!).use {
            every { KafkaSender.create<String, String>(any()) } returns mockk()
}
```
Also, I don't need it currently, but is it possible to also Spy on the static class (`staticSpyK`?).

**Comment by oleksiyp** [comment]
I think you shouldn't need that because staticMockk is wotking as spy. Please upgrade your version if it is not. It was changed recently. 

Btw you can use `staticMockk<KafkaSender>()` not to put qualified name.

**Comment by oleksiyp** [comment]
If you really need it, pless tell me. I'll consider adding some flags.

**Comment by Kleinendorst** [comment]
Ah, okay. Thank you.
And the relaxed mocking, is that also possible. 
Or is this specifically not possible because it's a spy?

**Comment by Kleinendorst** [comment]
I guess the addition would make static mocking more powerfull.
Also, do you consider changing the method name to: `staticSpyK` since it is technically a spy?

**Comment by oleksiyp** [comment]
It is possible, but need changes. And not sure I understand how valuble usecase is

**Comment by Kleinendorst** [comment]
Ah, okay. Anyway I won't need it currently, so I'll close this issue.

**Comment by Kleinendorst** [comment]
Thanks for the help btw.
Maybe it would be good to change the readme to include static mocking
using the method you just mentioned. The provided example is a bit vague also because it includes
the filename extension in the declaration.
